---
- name: Creates directory
  file:
    path: ~/web2
    state: directory


- name: "extract zipped artifact"
  unarchive: 
    src: "files/artifact.tar.gz"
    dest: "~/web2"

- name: "Installing node"
  shell: |
    cd ~/web2
    npm i
    cd ~/web2/dist
    pm2 stop default
    pm2 start main.js