---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: ~/web3
    state: directory


- name: "extract zipped artifact"
  unarchive: 
    src: "files/artifact.tar.gz"
    dest: "~/web3"


- name: "Installing node"
  shell: |
    cd ~/web3
    npm i
    pm2 stop default
    pm2 start npm -- start